// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class Test1Test {
  private ChromeDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    // Test name: Test1
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.google.com.ua/");
    // 2 | setWindowSize | 1000x600 | 
    //driver.manage().window().setSize(new Dimension(1000, 600));
    // 3 | type | name=q | qa course
    driver.findElement(By.name("q")).sendKeys("qa course");
    // 4 | sendKeys | name=q | ${KEY_ENTER}
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    // 5 | assertText | css=.g:nth-child(2) .LC20lb | изучайте Quality Assurance онлайн | Coursera
    driver.manage().timeouts().implicitlyWait(10000, TimeUnit.SECONDS);
    assertThat(driver.findElement(By.partialLinkText("Top Quality Assurance Courses Online - Updated [May 2022]")).getText(), is("Top Quality Assurance Courses Online - Updated [May 2022]"));
  }
}
